/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package es.ulpgc.diu.app.fx;

import es.ulpgc.diu.model.MatrixFilter;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import es.ulpgc.diu.view.MatrixDisplay;

/**
 *
 * @author Usuario
 */
public class MatrixResultPanel extends javax.swing.JPanel implements MatrixDisplay {

    private MatrixFilter matrixFilter;
    private JTextArea resultTextArea;
    private JScrollPane resultScrollPane;

    /**
     * Creates new form MatrixResultPanel
     */
    public MatrixResultPanel() {
        //initComponents();
        this.resultTextArea = new JTextArea();
        this.resultScrollPane = new JScrollPane();
        load();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void display(MatrixFilter matrixFilter) {
        this.matrixFilter = matrixFilter;
        this.resultTextArea.setText(this.matrixFilter.getFilteredMatrix());
    }

    @Override
    public void change() {
        this.resultTextArea.setText("");
        this.resultTextArea.setText(this.matrixFilter.getFilteredMatrix());
    }

    private void load() {
        this.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultado de la Matriz"));

        resultTextArea.setEditable(false);
        resultTextArea.setColumns(20);
        resultTextArea.setRows(5);
        resultTextArea.setEnabled(true);
        resultScrollPane.setViewportView(resultTextArea);

        javax.swing.GroupLayout resultPanelLayout = new javax.swing.GroupLayout(this);
        this.setLayout(resultPanelLayout);
        resultPanelLayout.setHorizontalGroup(
            resultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(resultScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                .addContainerGap())
        );
        resultPanelLayout.setVerticalGroup(
            resultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(resultScrollPane)
                .addContainerGap())
        );
    }

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
