//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Avatar.java
//  @ Date : 01/05/2020
//  @ Author : 
//
//


package preguntadosApp;

public class Avatar extends Imagen {
    private boolean publico;
    
    /**
     * Constructor para crear el avatar del usuarios
     * 
     * @param alto Altura de la imagen (en pixeles)
     * @param ancho Anchura de la imagen (en pixeles)
     * @param nombre nombre de la imagen
     * @param publico Indicar si el avatar es publico o no de base.
     */
    public Avatar(int alto, int ancho, String nombre, boolean publico) {
        super(alto, ancho, nombre);
        this.publico = publico;
    }
    
    /**
     * Metodo para indicar si el avarte es publico o privado.
     * 
     * @param value valor para activar el avatar de cara al publico.
     */
    public void setPublico(boolean value) {
        this.publico = value;
    }
}
