//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Bonificaci�n.java
//  @ Date : 01/05/2020
//  @ Author : 
//
//

package preguntadosApp;

public class Bonificacion implements Comparable<Bonificacion> {
	private String nombre;
	private int idBonificacion;
	private int precio;

        public Bonificacion() {
            this.nombre = "";
            this.idBonificacion = this.hashCode() * 13;
            this.precio = 0;
        }

        public Bonificacion(String nombre, int precio) {
            this.nombre = nombre;
            this.idBonificacion = this.hashCode() * 13;
            this.precio = precio;
        }

	public void setPrecio(int precio) {
	    this.precio = precio;
	}
	
	public void setNombre( String nombre) {
	    this.nombre = nombre;
	}
	
	public String getNombre() {
	    return this.nombre;
	}
	
	public int getId() {
	    return this.idBonificacion;
	}
	
	public int getPrecio() {
	    return this.precio;
	}

        @Override
        public int compareTo(Bonificacion b) {
            return ((Integer)this.idBonificacion).compareTo((Integer)b.getId());
        }

        /**COMPARETO**/
}
