//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Credito.java
//  @ Date : 01/05/2020
//  @ Author : 
//
//


package preguntadosApp;

public class Credito {
    int cantidad;
}
