//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : DatosCuenta.java
//  @ Date : 01/05/2020
//  @ Author : 
//
//

package preguntadosApp;


public class DatosCuenta {
	String contrasena;
	String email;
	Avatar avatar;
	String nombre;
}
