//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : DoblePuntuaci�n.java
//  @ Date : 01/05/2020
//  @ Author : 
//
//

package preguntadosApp;


public class DoblePuntuacion extends Bonificacion {
	public int modificador;
	public void setPuntuacion(int puntuacion) {
	
	}
}
