//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ElegirCategor�a.java
//  @ Date : 01/05/2020
//  @ Author : 
//
//


package preguntadosApp;

public class ElegirCategoria extends Bonificacion {
        int categoria; //Modificacion con respecto al diagrama

        public ElegirCategoria() {
            super();
            this.categoria = 0;
        }

        public ElegirCategoria(int categoria) {
            super();
            this.categoria = categoria;
        }

        //Sobra
	public void generarOpciones() {
	
	}
	
	public void setCategoria(int categoria) {
            this.categoria = categoria;	
	}
	
        //Sobra
	/*public int setOpcion() {
	
	}*/
}
