//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Estad�ticasPartida.java
//  @ Date : 01/05/2020
//  @ Author : 
//
//


package preguntadosApp;

public class EstadisticasPartida {
	private int CodPart;
	private int ID;
	private int aciertosJ1;
	private int aciertosJ2;
	private int fallosJ1;
	private int fallosJ2;
	public void addEntrada() {
	
	}
}
