//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : EstadoJugador.java
//  @ Date : 01/05/2020
//  @ Author : 
//
//


package preguntadosApp;

public class EstadoJugador {
	public Object activo;
	public Object desconectado;
	public Object enPartida;
	public Object enEspera;
}
