//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Formato.java
//  @ Date : 01/05/2020
//  @ Author : 
//
//

package preguntadosApp;


public class Formato {
	public Object png;
	public Object jpg;
	public Object bmp;
	public Object svg;
}
