//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Imagen.java
//  @ Date : 01/05/2020
//  @ Author : 
//
//

package preguntadosApp;

public abstract class Imagen {
        public int codImg;
	private int alto;
	private int ancho;
	private String nombre;
	public Jugador modifica;
	
        /**
         * Constructor por defecto
         * 
         * @param codImg Identificador de la imagen
         * @param alto 
         * @param ancho
         * @param nombre 
         */
	public Imagen(int alto, int ancho, String nombre) {
            this.codImg = (this.hashCode()*13);
            this.alto = alto;
            this.ancho = ancho;
            this.nombre = nombre;
	}
	
        /**
         * 
         * @return 
         */
	public int getAlto() {
            return alto;
	}
	
        /**
         * 
         * @return 
         */
	public int getAncho() {
	    return ancho;
        }
        
	public void setAlto(int alto) {
            this.alto = alto;
	}
	
        /**
         * 
         * @param ancho
         * @return 
         */
	public void setAncho(int ancho) {
	    this.ancho = ancho;
	}
        
        /**
         * 
         * @return 
         */
	public Formato getFormato() {
	    return new Formato();
	}
	
        /**
         * 
         * @return 
         */
	public String getNombre() {
	    return nombre;
	}
}
