//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Jugador.java
//  @ Date : 01/05/2020
//  @ Author : 
//
//

package preguntadosApp;
import java.util.ArrayList;

public class Jugador implements Comparable<Jugador> {
	private int id;
	private Credito creditos;
	private int totalAciertos;
	private int totalFallos;
	private ArrayList<Jugador> amigos;
        private ArrayList<Bonificacion> bonificaciones;
        private DatosCuenta datos; 
        
        /**
         * 
         */
        public Jugador(String contrasena, String email, String nombre){
            this.id = this.hashCode()*13;
            
            //Datos del jugador
            this.datos = new DatosCuenta();
            this.datos.avatar = null;
            this.datos.contrasena = contrasena;
            this.datos.email = email;
            this.datos.nombre = nombre;
            
            //Datos de la cuenta
            this.bonificaciones = new ArrayList();
            this.creditos = new Credito();
            this.creditos.cantidad = 0;
        }
        
        /**
         * 
         * @param email 
         */
	public void setEmail(String email) {
            this.datos.email = email;
	}
	
        /**
         * 
         * @param contrasena 
         */
	public void setPassword(String contrasena) {
            this.datos.contrasena = contrasena;
	}
	
        /**
         * 
         * @param tipo 
         */
	public void setTipo(TipoJugador tipo) {
            
	}
	
        /**
         * 
         * @param creditos 
         */
	public void setCreditos(Credito creditos) {
            this.creditos = creditos;
	}
	
	public void setEstado(EstadoJugador ej) {
            
	}
	
        /**
         * 
         * @return 
         */
	public TipoJugador getTipo() {
            return new TipoJugador();
	}
        
        /*
	public EstadoJugador getEstado() 
	}
	*/
	public int getNumBonificaciones() {
            return this.bonificaciones.size();
	}
        
        /**
         * 
         * @param jugador
         * @return 
         */
	public boolean addAmigo(Jugador jugador) {
            return this.amigos.add(jugador);
	}
        
        /**
         * 
         * @return 
         */
	public int getCredito() {
            return this.creditos.cantidad;
	}
	
        /**
         * 
         * @return 
         */
	public String getEmail() {
            return this.datos.email;
	}
	
        /**
         * 
         * @return 
         */
	public String getPassword() {
            return this.datos.contrasena;
        }
        
        /**
         * 
         * @param nuevos 
         */
	public void incrementarCredito(int nuevos) {
            this.creditos.cantidad = this.getCredito()+nuevos;
	}
	
        /**
         * 
         * @param retirar
         * @return 
         */
	public boolean decrementarCredito(int retirar) {
            if(this.getCredito()-retirar < 0){
                return false;
            }
            this.creditos.cantidad = this.getCredito()-retirar;
            return true;
	}
	
        /**
         * 
         * @param anadir
         * @return 
         */
	public boolean addBonificacion(Bonificacion anadir) {
            return this.bonificaciones.add(anadir);
	}
	
        /**
         * 
         * @param retirar
         * @return 
         */
	public boolean removeBonificacion(Bonificacion retirar) {
            return this.bonificaciones.remove(retirar);
	}
        
        /**
         * 
         * @param j
         * @return 
         */
        @Override
        public int compareTo(Jugador j){
            if(this.getEmail().compareTo(j.getEmail())==0){
                return 0;
            } else {
                return this.getEmail().compareTo(j.getEmail());
            }
        } 
}

