//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Partida.java
//  @ Date : 01/05/2020
//  @ Author : 
//
//


package preguntadosApp;

public class Partida implements Comparable<Partida> {
	private int CodPart;
	private Jugador jugador1;
	private Jugador jugador2;
	private int turnoJugador;
	private int aciertosJ1;
	private int aciertosJ2;
	private boolean pausa;
	private int puntuacionJ1;
	private int puntuacionJ2;
	public void setJugador1(Jugador player1) {
	
	}
	
	public void setJugador2(Jugador player2) {
	
	}
	
	public void setTurnoJugador(int player) {
	
	}
	
        /*
	public Jugador getJugador1() {
	
	}
	
	public Jugador getJugador2() {
	
	}
	
	public int getTurnoActual() {
	
	}
	
	public void pausar(Object boolean true) {
	
	}
	
	public void continuar(Object boolean false) {
	
	}
	
	public void iniciar() {
	
	}
	
	public Ronda ini8ciarRonda(Partida partida.this, Jugador player) {
	
	}
	
	public void finializarPartida() {
	
	}
	
	public EstadoPartida getEstado() {
	
	}
        */
        @Override
        public int compareTo(Partida j){
            return 0;
        } 
}
