//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : PreguntaConRespuesta.java
//  @ Date : 01/05/2020
//  @ Author : 
//
//


package preguntadosApp;

public class PreguntaConRespuesta {
	private int CodPreg;
	private int CodResp;
	private boolean esCorrecta;
	public void ad() {
	
	}
}
