//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Preguntados.java
//  @ Date : 01/05/2020
//  @ Author : 
//
//


package preguntadosApp;

public class Preguntados {
	public int partidasActivas;
        
        /*public static void main(String arg[]){
            setupPreguntas();
            //Iniciar registros
        }*/
        
        public static void setupPreguntas(){
            Respuesta r1 = new Respuesta("Blanco");
            Respuesta r2 = new Respuesta("Verde");
            Respuesta r3 = new Respuesta("Azul");
            Respuesta r4 = new Respuesta("Rojo");
            
            Respuesta r5 = new Respuesta("Nilo");
            Respuesta r6 = new Respuesta("Missisipi");
            Respuesta r7 = new Respuesta("Amazonas");
            Respuesta r8 = new Respuesta("Danubio");
            
            Pregunta p1 = new Pregunta("¿De que color es el caballo blanco de Santiago?", 6);
            Pregunta p2 = new Pregunta("¿Qué río es el más largo del mundo?", 4);
            
            p1.addRespuesta(r1);
            p1.addRespuesta(r2);
            p1.addRespuesta(r3);
            p1.addRespuesta(r4);
            
            p2.addRespuesta(r5);
            p2.addRespuesta(r6);
            p2.addRespuesta(r7);
            p2.addRespuesta(r8);
            
            p1.setCorrecta(r1);
            p2.setCorrecta(r7);
            
            System.out.println();
            System.out.println(p1.getEnunciado());
            String[] p1p = p1.getRespuestas();
            for(int i=0; i<p1p.length; i++){
                System.out.println(p1p[i]);
            }
            System.out.println("La correcta es: "+p1.getCorrecta().getTexto()+"\n");
            
            System.out.println(p2.getEnunciado());
            String[] p2p = p2.getRespuestas();
            for(int i=0; i<p2p.length; i++){
                System.out.println(p2p[i]);
            }
            System.out.println("La correcta es: "+p2.getCorrecta().getTexto()+"\n");
        }
	/*public void verPerfil() {
	
	}*/
	/*
	public Partida nuevaPartida crearPartida() {
	
	}
	
	public void verPartidasDisponibles(Object RegistroPartidas registro) {
	
	}
	
	public void verOpciones() {
	
	}
	
	private void setupPreguntados() {
	
	}*/
}
