//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Redemption.java
//  @ Date : 01/05/2020
//  @ Author : 
//
//


package preguntadosApp;

public class Redemption extends Bonificacion {
        private boolean status; //Modificacion con respecto al diagrama

        public Redemption() {
            super();
            this.status = false;
        }

        public Redemption(boolean status) {
            super();
            this.status = status;
        }

        public void setRedemption(boolean status) {
            this.status = status;
        }
}
