//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : RegistroPartidas.java
//  @ Date : 01/05/2020
//  @ Author : 
//
//




public class RegistroPartidas {
	public void mostrar() {
	
	}
	
	public void addNuevaEntrada() {
	
	}
}
