//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : RondaPregunta.java
//  @ Date : 01/05/2020
//  @ Author : 
//
//


package preguntadosApp;

public class RondaPregunta {
	private int CodRnd;
	private int CodPreg;
	private Jugador jugador;
	public void addEntrada() {
	
	}
}
