//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Ronda.java
//  @ Date : 01/05/2020
//  @ Author : 
//
//


package preguntadosApp;

public class Ronda {
	public int idRonda;
	private boolean activa;
	private boolean redemption;
        
        /*
	public void setTipoDePregunta(TipoPregunta t) {
	
	}
	
	public int girarRuleta() {
	
	}
	
	public void incPuntuacion(Jugador j) {
	
	}
	
	public void mostrarPregunta(Pregunta p) {
	
	}
	
	public void actualizarPuntuacion(int puntuacion) {
	
	}
        */
}
