//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : RondaPartida.java
//  @ Date : 01/05/2020
//  @ Author : 
//
//


package preguntadosApp;

public class RondaPartida {
	private int CodPart;
	private int CodRonda;
	public Jugador jugador;
	public boolean acertada;
	public void addEntrada() {
	
	}
}
