//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : TipoJugador.java
//  @ Date : 01/05/2020
//  @ Author : 
//
//


package preguntadosApp;

public class TipoJugador {
	public Object Premium;
	public Object Normal;
}
