//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : TipoImagen.java
//  @ Date : 01/05/2020
//  @ Author : 
//
//


package preguntadosApp;

public class TipoImagen {
	public Object basica;
	public Object personal;
}
