//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : TriplePuntuaci�n.java
//  @ Date : 01/05/2020
//  @ Author : 
//
//


package preguntadosApp;

public class TriplePuntuacion extends Bonificacion {
	public int modificador;
        
        public TriplePuntuacion() {
            super();
            this.modificador = 3;        
        }

	public void setPuntuacion(int puntuacion) {
	    puntuacion = puntuacion*this.modificador; // Corregir
	}
}
