//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Turno.java
//  @ Date : 01/05/2020
//  @ Author : 
//
//


package preguntadosApp;

public class Turno {
	private Jugador Actual;
}
