#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include "mn_calculo_ceros.h"


/// CALCULO INTERÉS APLICADO A 3 AÑOS
/// UNA PERSONA INVIERTE 1000 EUROS CADA AÑO EN UN BANCO Y AL
/// FINAL DEL AÑO 3 LE DAN 3200 EUROS. THE TASA DE INTERÉS x LE HAN APLICADO ANUALMENTE
/// SI TENEMOS EN CUENTA QUE LA FÓRMULA QUE CALCULA LA SUMA TOTAL (3200 EUROS) ES

/// S(x)= 1000*(1+x)+1000*(1+x)*(1+x)+1000*(1+x)*(1+x)*(1+x)

/// CALCULAR EL VALOR DE x POR EL MÉTODO DE LA BISECCIÓN SABIENDO QUE LA TASA DE INTERÉS BUSCADO
/// SE ENCUENTRA ENTRE EL 0% Y EL 10%

/// CUALQUIER OTRO PARÁMETRO DEL MÉTODO LO TIENE QUE ELEGIR EL PROPIO ALUMNO

/// NOTA : HACER MAS OPERACIONES DE LAS INDISPENSABLES BAJA LA CALIFICACIÓN

real interes ()
{
  /// HACER ALUMNO


}


