/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package es.ulpgc.diu.app;

import es.ulpgc.diu.db.SQLHelper;
import java.awt.Component;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.io.FileNotFoundException;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Usuario
 */
public class App extends javax.swing.JFrame {

    private SQLHelper sqlHelper;
    private Connection connection;
    /**
     * Creates new form app
     */
    public App() {
        initBackEndLogic();
        initComponents();
        this.queryResultList.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        this.setLocationRelativeTo(null);
        initLoginDialog();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginDialog = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        usernameLabel = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        jPanel3 = new javax.swing.JPanel();
        loginButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        remoteDbButton = new javax.swing.JRadioButton();
        localDbButton = new javax.swing.JRadioButton();
        scriptDbButton = new javax.swing.JRadioButton();
        selectionModeButtonGroup = new javax.swing.ButtonGroup();
        dbSelectorButtonGroup = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        simpleSelectionButton = new javax.swing.JToggleButton();
        intervalSelectionButton = new javax.swing.JToggleButton();
        multipleSelectionButton = new javax.swing.JToggleButton();
        updateDB = new javax.swing.JButton();
        clearListButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        queryResultList = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableFieldsTextArea = new javax.swing.JTextArea();
        jPanel8 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        userMenu = new javax.swing.JMenu();
        logoutMenu = new javax.swing.JMenuItem();

        loginDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        loginDialog.setTitle("Iniciar Sesión");
        loginDialog.setMaximumSize(new java.awt.Dimension(390, 200));
        loginDialog.setMinimumSize(new java.awt.Dimension(390, 200));
        loginDialog.setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        loginDialog.setPreferredSize(new java.awt.Dimension(390, 200));
        loginDialog.setResizable(false);

        jPanel2.setLayout(new java.awt.GridLayout(2, 2, 30, 0));

        usernameLabel.setText("Usuario");
        jPanel2.add(usernameLabel);
        jPanel2.add(usernameField);

        passwordLabel.setText("Contraseña");
        jPanel2.add(passwordLabel);
        jPanel2.add(passwordField);

        jPanel3.setLayout(new java.awt.GridLayout(1, 2, 30, 0));

        loginButton.setBackground(new java.awt.Color(115, 209, 146));
        loginButton.setText("Acceder");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        jPanel3.add(loginButton);

        exitButton.setText("Salir");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        jPanel3.add(exitButton);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel9.setLayout(new java.awt.GridLayout(1, 3));

        dbSelectorButtonGroup.add(remoteDbButton);
        remoteDbButton.setText("BD Remoto");
        remoteDbButton.setEnabled(false);
        jPanel9.add(remoteDbButton);

        dbSelectorButtonGroup.add(localDbButton);
        localDbButton.setText("BD Local");
        localDbButton.setEnabled(false);
        jPanel9.add(localDbButton);

        dbSelectorButtonGroup.add(scriptDbButton);
        scriptDbButton.setSelected(true);
        scriptDbButton.setText("Script SQL");
        jPanel9.add(scriptDbButton);

        javax.swing.GroupLayout loginDialogLayout = new javax.swing.GroupLayout(loginDialog.getContentPane());
        loginDialog.getContentPane().setLayout(loginDialogLayout);
        loginDialogLayout.setHorizontalGroup(
            loginDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(loginDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        loginDialogLayout.setVerticalGroup(
            loginDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginDialogLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Selector de Tablas");

        jPanel6.setBackground(new java.awt.Color(142, 218, 129));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel5.setOpaque(false);
        jPanel5.setLayout(new java.awt.GridLayout(5, 0, 0, 20));

        selectionModeButtonGroup.add(simpleSelectionButton);
        simpleSelectionButton.setSelected(true);
        simpleSelectionButton.setText("Simple");
        simpleSelectionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpleSelectionButtonActionPerformed(evt);
            }
        });
        jPanel5.add(simpleSelectionButton);

        selectionModeButtonGroup.add(intervalSelectionButton);
        intervalSelectionButton.setText("Intervalo");
        intervalSelectionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intervalSelectionButtonActionPerformed(evt);
            }
        });
        jPanel5.add(intervalSelectionButton);

        selectionModeButtonGroup.add(multipleSelectionButton);
        multipleSelectionButton.setText("Multiples Intervalos");
        multipleSelectionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multipleSelectionButtonActionPerformed(evt);
            }
        });
        jPanel5.add(multipleSelectionButton);

        updateDB.setBackground(new java.awt.Color(204, 204, 0));
        updateDB.setText("Recargar");
        updateDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateDBActionPerformed(evt);
            }
        });
        jPanel5.add(updateDB);

        clearListButton.setBackground(new java.awt.Color(255, 102, 102));
        clearListButton.setText("Limpiar Selección");
        clearListButton.setToolTipText("");
        clearListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearListButtonActionPerformed(evt);
            }
        });
        jPanel5.add(clearListButton);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Opciones");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        jPanel7.setLayout(new java.awt.GridLayout(1, 2, 30, 0));

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        queryResultList.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        queryResultList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                queryResultListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(queryResultList);

        jPanel7.add(jScrollPane1);

        tableFieldsTextArea.setColumns(20);
        tableFieldsTextArea.setRows(5);
        tableFieldsTextArea.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        tableFieldsTextArea.setEnabled(false);
        tableFieldsTextArea.setFocusable(false);
        jScrollPane2.setViewportView(tableFieldsTextArea);

        jPanel7.add(jScrollPane2);

        jPanel8.setBackground(new java.awt.Color(174, 225, 174));
        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel8.setForeground(new java.awt.Color(204, 255, 204));
        jPanel8.setLayout(new java.awt.GridLayout(1, 2, 30, 0));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Tablas disponibles");
        jPanel8.add(jLabel2);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Campos de cada tabla");
        jPanel8.add(jLabel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        userMenu.setBackground(new java.awt.Color(0, 153, 51));
        userMenu.setText("File");
        userMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        logoutMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        logoutMenu.setText("Cerrar Sesión");
        logoutMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutMenuActionPerformed(evt);
            }
        });
        userMenu.add(logoutMenu);

        jMenuBar1.add(userMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        this.closeApp(loginDialog);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        String user = this.usernameField.getText();
        String password = String.copyValueOf(this.passwordField.getPassword());
        if(checkData(user, password)){
            try {
                this.connection = this.sqlHelper.conectToLocalFileDatabase(user, password);
                //this.connection = this.sqlHelper.conectToLocalDatabase(user, password);
                //this.connection = this.sqlHelper.conectToRemoteDatabase(user, password);
                JOptionPane.showMessageDialog(loginDialog, "Conexión realizada con éxito", "Conexión realizada", JOptionPane.INFORMATION_MESSAGE);
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
            }
            setConnection(user);
        }
    }//GEN-LAST:event_loginButtonActionPerformed

    private void setConnection(String user) {
        if(this.connection != null){
            this.userMenu.setText(user);
            this.QueryDB();
            this.loginDialog.dispose();
        }
    }

    private boolean checkData(String user, String password) {
        if(user.equals("")){
            JOptionPane.showMessageDialog(loginDialog, "El nombre de usuario no puede estar vacío", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if(password.equals("")){
            JOptionPane.showMessageDialog(loginDialog, "La contraseña no puede estar vacía", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }
    
    private void logoutMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutMenuActionPerformed
        closeApp(this);
    }//GEN-LAST:event_logoutMenuActionPerformed

    private void simpleSelectionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpleSelectionButtonActionPerformed
        this.queryResultList.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }//GEN-LAST:event_simpleSelectionButtonActionPerformed

    private void intervalSelectionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intervalSelectionButtonActionPerformed
        this.queryResultList.setSelectionMode(ListSelectionModel.SINGLE_INTERVAL_SELECTION);
    }//GEN-LAST:event_intervalSelectionButtonActionPerformed

    private void multipleSelectionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multipleSelectionButtonActionPerformed
        this.queryResultList.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
    }//GEN-LAST:event_multipleSelectionButtonActionPerformed

    private void clearListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearListButtonActionPerformed
        this.queryResultList.clearSelection();
        this.tableFieldsTextArea.setText(new String());
    }//GEN-LAST:event_clearListButtonActionPerformed

    private void queryResultListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_queryResultListMouseClicked
        List<String> selectedRows = this.queryResultList.getSelectedValuesList();
        String tableFieldsList = "";
        for (String tableName : selectedRows) {
            ArrayList<Object> tableFields= SQLHelper.queryTablesData(this.connection, tableName);
            for (Object tableField : tableFields) {
                tableFieldsList += tableName + "." + (String) tableField + "\n";
            }
            tableFieldsList += "\n";
        }
        this.tableFieldsTextArea.setText(tableFieldsList);
    }//GEN-LAST:event_queryResultListMouseClicked

    private void updateDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateDBActionPerformed
        this.QueryDB();
    }//GEN-LAST:event_updateDBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }

    private void initLoginDialog() {
        this.loginDialog.addWindowListener(new WindowAdapter(){
            @Override
            public void windowClosing(WindowEvent e) {
                closeApp(loginDialog);
            }
        });
        this.loginDialog.setLocationRelativeTo(this);
        this.loginDialog.setAlwaysOnTop(true);
        this.loginDialog.setVisible(true);
    }

    private void initBackEndLogic() {
        this.addWindowListener(new WindowAdapter(){
            @Override
            public void windowClosing(WindowEvent e) {
                closeApp(null);
            }
        });
        this.sqlHelper = new SQLHelper();
    }
    
    private void closeApp(Component component){
        Component context = (component == null) ? this : component; 
        if(this.connection != null){
            try {
                this.connection.close();
            } catch (SQLException ex) {
                Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        JOptionPane.showMessageDialog(context, "Conexión cerrada con éxito", "Cierre de Sesión", JOptionPane.INFORMATION_MESSAGE);
        System.exit(0);
    }

    private void QueryDB() {
        String query = "SHOW TABLES";
        DefaultListModel<String> model = new DefaultListModel<>();
        ArrayList<Object> results = this.sqlHelper.launchQuery(this.connection, query);
        for (int i = 0; i < results.size(); i++) {
            model.add(i, (String) results.get(i));
        }
        this.queryResultList.setModel(model);
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearListButton;
    private javax.swing.ButtonGroup dbSelectorButtonGroup;
    private javax.swing.JButton exitButton;
    private javax.swing.JToggleButton intervalSelectionButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton localDbButton;
    private javax.swing.JButton loginButton;
    private javax.swing.JDialog loginDialog;
    private javax.swing.JMenuItem logoutMenu;
    private javax.swing.JToggleButton multipleSelectionButton;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JList<String> queryResultList;
    private javax.swing.JRadioButton remoteDbButton;
    private javax.swing.JRadioButton scriptDbButton;
    private javax.swing.ButtonGroup selectionModeButtonGroup;
    private javax.swing.JToggleButton simpleSelectionButton;
    private javax.swing.JTextArea tableFieldsTextArea;
    private javax.swing.JButton updateDB;
    private javax.swing.JMenu userMenu;
    private javax.swing.JTextField usernameField;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables


}
