/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package es.ulpgc.gs1.app.fx;

import es.ulpgc.gs1.helpers.FXHelper;
import es.ulpgc.gs1.model.data.Session;
import es.ulpgc.gs1.helpers.SQLHelper;
import es.ulpgc.gs1.model.data.RegisterData;
import es.ulpgc.gs1.model.data.db.SQLLoginSystem;
import es.ulpgc.gs1.model.data.db.SQLRegistrySystem;
import es.ulpgc.gs1.persistence.ExternalPanel;
import es.ulpgc.gs1.persistence.LoginSystem;
import es.ulpgc.gs1.persistence.RegistrySystem;
import java.awt.Component;
import java.awt.HeadlessException;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class MyErasmus extends javax.swing.JFrame {

    LoginSystem loginSystem;
    RegistrySystem registrySystem;
    Session session;
    /**
     * Creates new form MyErasmus
     */
    public MyErasmus() {
        initLogicComponents();
        initComponents();
        initApp();
    }

    private void initLogicComponents() {
        try {
            if(!SQLHelper.conectToLocalDatabase()){
                System.exit(0);
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(MyErasmus.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.session = new Session();
        this.loginSystem = new SQLLoginSystem(this.session);
        this.registrySystem = new SQLRegistrySystem();
        
    }
    
    private void initApp() {
        setLogo();
        configureDialogs();
        this.setLocationRelativeTo(null);
        this.completeProfilePanel.setVisible(false);
        this.setVisible(true);
        if(this.session.getUsername() == null){
            this.loginDialog.setVisible(true);
        }
    }

    private void setLogo() {
        ClassLoader classLoader = getClass().getClassLoader();
        Icon logo = new ImageIcon(classLoader.getResource("logo.png"));
        this.logoPNG.setIcon(logo);
    }
    
    private void configureDialogs() {
        this.loginDialog.pack();
        this.registerDialog.pack();
        this.studentDataDialog.pack();
        this.landlordDataDialog.pack();
        this.universityDataDialog.pack();
        this.loginDialog.setLocationRelativeTo(this);
        this.registerDialog.setLocationRelativeTo(this);
        this.studentDataDialog.setLocationRelativeTo(this);
        this.landlordDataDialog.setLocationRelativeTo(this);
        this.universityDataDialog.setLocationRelativeTo(this);
        addSystemCloseEvents();
    }

    
    private void addSystemCloseEvents(){
        this.loginDialog.addWindowListener(new WindowAdapter(){
            @Override
            public void windowClosing(WindowEvent e) {
                loginDialog.dispose();
                closeApp();
            }
        });
        this.registerDialog.addWindowListener(new WindowAdapter(){
            @Override
            public void windowClosing(WindowEvent e) {
                registerDialog.setVisible(false);
                loginDialog.setVisible(true);
                closeApp();
            }
        });
        this.studentDataDialog.addWindowListener(new WindowAdapter(){
            @Override
            public void windowClosing(WindowEvent e) {
                studentDataDialog.dispose();
                closeApp();
            }
        });
        this.landlordDataDialog.addWindowListener(new WindowAdapter(){
            @Override
            public void windowClosing(WindowEvent e) {
                landlordDataDialog.dispose();
                closeApp();
            }
        });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginDialog = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        userTextField = new javax.swing.JTextField();
        passwordTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        bLogin = new javax.swing.JButton();
        registerInLoginButton = new javax.swing.JButton();
        registerInLoginButton1 = new javax.swing.JButton();
        registerDialog = new javax.swing.JDialog();
        registryPanel = new javax.swing.JPanel();
        registryPanelTitle = new javax.swing.JLabel();
        confirmPasswordRegistryLabel = new javax.swing.JLabel();
        confirmPasswordRegistryField = new javax.swing.JTextField();
        passwordRegistryLabel = new javax.swing.JLabel();
        passwordRegistryField = new javax.swing.JTextField();
        emailRegistryLabel = new javax.swing.JLabel();
        emailRegistryField = new javax.swing.JTextField();
        userRegistryLabel = new javax.swing.JLabel();
        userRegistryField = new javax.swing.JTextField();
        userTypeComboBoxLabel = new javax.swing.JLabel();
        userTypeComboBox = new javax.swing.JComboBox<>();
        destinarionComboBoxLabel = new javax.swing.JLabel();
        destinarionComboBox = new javax.swing.JComboBox<>();
        goBackToLoginButton = new javax.swing.JButton();
        registerBottonInRegister = new javax.swing.JButton();
        modificarAlumnoDialog = new javax.swing.JDialog();
        registryPanel1 = new javax.swing.JPanel();
        registryPanelTitle1 = new javax.swing.JLabel();
        confirmPasswordRegistryLabel1 = new javax.swing.JLabel();
        confirmPasswordRegistryField1 = new javax.swing.JTextField();
        passwordRegistryLabel1 = new javax.swing.JLabel();
        passwordRegistryField1 = new javax.swing.JTextField();
        emailRegistryLabel1 = new javax.swing.JLabel();
        emailRegistryField1 = new javax.swing.JTextField();
        userRegistryLabel1 = new javax.swing.JLabel();
        destinarionComboBoxLabel1 = new javax.swing.JLabel();
        destinarionComboBox1 = new javax.swing.JComboBox<>();
        goBackToLoginButton1 = new javax.swing.JButton();
        registerBottonInRegister1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        modificarArrendadorDialog = new javax.swing.JDialog();
        registryPanel2 = new javax.swing.JPanel();
        registryPanelTitle2 = new javax.swing.JLabel();
        confirmPasswordRegistryLabel2 = new javax.swing.JLabel();
        confirmPasswordRegistryField2 = new javax.swing.JTextField();
        passwordRegistryLabel2 = new javax.swing.JLabel();
        passwordRegistryField2 = new javax.swing.JTextField();
        emailRegistryLabel2 = new javax.swing.JLabel();
        emailRegistryField2 = new javax.swing.JTextField();
        userRegistryLabel2 = new javax.swing.JLabel();
        destinarionComboBoxLabel2 = new javax.swing.JLabel();
        destinarionComboBox2 = new javax.swing.JComboBox<>();
        goBackToLoginButton2 = new javax.swing.JButton();
        registerBottonInRegister2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        studentDataDialog = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        startDateField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        endDateField = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        passportField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        mobilityCombo = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        cancelStudentButton = new javax.swing.JButton();
        acceptStudentButton = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        landlordDataDialog = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        landlordNifField = new javax.swing.JTextField();
        cancelLanlordButton = new javax.swing.JButton();
        acceptLandlordButton = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        universityDataDialog = new javax.swing.JDialog();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        universityCodeField = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        universityPublicStatus = new javax.swing.JCheckBox();
        cancelUniversityButton = new javax.swing.JButton();
        acceptUniversityButton = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jDialog2 = new javax.swing.JDialog();
        roomsLabel = new javax.swing.JLabel();
        avaliable_surfaceLabel = new javax.swing.JLabel();
        durationLabel = new javax.swing.JLabel();
        adv_idLabel = new javax.swing.JLabel();
        landlord_idLabel = new javax.swing.JLabel();
        adv_idField = new javax.swing.JTextField();
        durationField = new javax.swing.JTextField();
        avaliable_surfaceField = new javax.swing.JTextField();
        roomsField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        landlord_idField = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        profilePanel = new javax.swing.JPanel();
        logoPanel = new javax.swing.JPanel();
        logoPNG = new javax.swing.JLabel();
        UserPicturePanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        userDataPanel = new javax.swing.JPanel();
        userTitleLabel = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        destinationTitleLabel = new javax.swing.JLabel();
        destinoLabel = new javax.swing.JLabel();
        usertypeTitleLabel = new javax.swing.JLabel();
        userTypeLabel = new javax.swing.JLabel();
        extraLabelTitle1 = new javax.swing.JLabel();
        extraLabel1 = new javax.swing.JLabel();
        extraLabelTitle2 = new javax.swing.JLabel();
        extraLabel2 = new javax.swing.JLabel();
        completeProfilePanel = new javax.swing.JPanel();
        completeProfileButton = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        tabbedPanel = new javax.swing.JTabbedPane();
        menuBar = new javax.swing.JMenuBar();
        logoutMenu = new javax.swing.JMenu();
        closeSessionItem = new javax.swing.JMenuItem();
        exitItem = new javax.swing.JMenuItem();
        editProfileMenu = new javax.swing.JMenu();

        loginDialog.setMinimumSize(new java.awt.Dimension(350, 300));
        loginDialog.setModal(true);
        loginDialog.setResizable(false);

        jPanel3.setBackground(new java.awt.Color(46, 103, 212));
        jPanel3.setMaximumSize(new java.awt.Dimension(328, 300));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Iniciar sesion");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Usuario: ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Contraseña:");

        bLogin.setText("Iniciar sesión");
        bLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLoginActionPerformed(evt);
            }
        });

        registerInLoginButton.setForeground(new java.awt.Color(0, 0, 255));
        registerInLoginButton.setText("¿No tienes cuenta? Registrarme");
        registerInLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerInLoginButtonActionPerformed(evt);
            }
        });

        registerInLoginButton1.setForeground(new java.awt.Color(255, 0, 0));
        registerInLoginButton1.setText("Salir");
        registerInLoginButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerInLoginButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 24, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passwordTextField)
                            .addComponent(userTextField)))
                    .addComponent(registerInLoginButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(registerInLoginButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(userTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(bLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(registerInLoginButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(registerInLoginButton1)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout loginDialogLayout = new javax.swing.GroupLayout(loginDialog.getContentPane());
        loginDialog.getContentPane().setLayout(loginDialogLayout);
        loginDialogLayout.setHorizontalGroup(
            loginDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        loginDialogLayout.setVerticalGroup(
            loginDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        registerDialog.setAlwaysOnTop(true);
        registerDialog.setMinimumSize(new java.awt.Dimension(388, 359));

        registryPanel.setBackground(new java.awt.Color(46, 103, 212));
        registryPanel.setForeground(new java.awt.Color(255, 255, 255));
        registryPanel.setMaximumSize(new java.awt.Dimension(388, 359));
        registryPanel.setMinimumSize(new java.awt.Dimension(388, 359));

        registryPanelTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        registryPanelTitle.setForeground(new java.awt.Color(255, 255, 255));
        registryPanelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registryPanelTitle.setText("Registro");

        confirmPasswordRegistryLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        confirmPasswordRegistryLabel.setForeground(new java.awt.Color(255, 255, 255));
        confirmPasswordRegistryLabel.setText("Repetir contraseña:");

        passwordRegistryLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        passwordRegistryLabel.setForeground(new java.awt.Color(255, 255, 255));
        passwordRegistryLabel.setText("Contraseña: ");

        emailRegistryLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        emailRegistryLabel.setForeground(new java.awt.Color(255, 255, 255));
        emailRegistryLabel.setText("Correo electrónico:");

        userRegistryLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        userRegistryLabel.setForeground(new java.awt.Color(255, 255, 255));
        userRegistryLabel.setText("Nombre de Usuario:");

        userTypeComboBoxLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        userTypeComboBoxLabel.setForeground(new java.awt.Color(255, 255, 255));
        userTypeComboBoxLabel.setText("Tipo de usuario:");

        userTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estudiante", "Universidad", "Arrendador" }));

        destinarionComboBoxLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        destinarionComboBoxLabel.setForeground(new java.awt.Color(255, 255, 255));
        destinarionComboBoxLabel.setText("País Destino:");

        destinarionComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No lo se aún", "Polonia", "Rumanía", "Italia" }));
        destinarionComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destinarionComboBoxActionPerformed(evt);
            }
        });

        goBackToLoginButton.setBackground(new java.awt.Color(51, 153, 255));
        goBackToLoginButton.setText("Volver atrás");
        goBackToLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBackToLoginButtonActionPerformed(evt);
            }
        });

        registerBottonInRegister.setBackground(new java.awt.Color(51, 153, 255));
        registerBottonInRegister.setText("Registrar");
        registerBottonInRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBottonInRegisterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout registryPanelLayout = new javax.swing.GroupLayout(registryPanel);
        registryPanel.setLayout(registryPanelLayout);
        registryPanelLayout.setHorizontalGroup(
            registryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registryPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(registryPanelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(133, 133, 133))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(registryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(registryPanelLayout.createSequentialGroup()
                        .addComponent(goBackToLoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                        .addComponent(registerBottonInRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(registryPanelLayout.createSequentialGroup()
                        .addGroup(registryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passwordRegistryLabel)
                            .addComponent(confirmPasswordRegistryLabel)
                            .addComponent(userTypeComboBoxLabel)
                            .addComponent(destinarionComboBoxLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailRegistryLabel)
                            .addComponent(userRegistryLabel))
                        .addGap(18, 18, 18)
                        .addGroup(registryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(destinarionComboBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(userTypeComboBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(confirmPasswordRegistryField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(passwordRegistryField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(emailRegistryField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(userRegistryField, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(28, 28, 28))
        );
        registryPanelLayout.setVerticalGroup(
            registryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(registryPanelTitle)
                .addGap(18, 18, 18)
                .addGroup(registryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userRegistryField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userRegistryLabel))
                .addGap(18, 18, 18)
                .addGroup(registryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailRegistryField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailRegistryLabel))
                .addGap(18, 18, 18)
                .addGroup(registryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordRegistryField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordRegistryLabel))
                .addGap(18, 18, 18)
                .addGroup(registryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmPasswordRegistryLabel)
                    .addComponent(confirmPasswordRegistryField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(registryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userTypeComboBoxLabel)
                    .addComponent(userTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(registryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(destinarionComboBoxLabel)
                    .addComponent(destinarionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(registryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerBottonInRegister)
                    .addComponent(goBackToLoginButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout registerDialogLayout = new javax.swing.GroupLayout(registerDialog.getContentPane());
        registerDialog.getContentPane().setLayout(registerDialogLayout);
        registerDialogLayout.setHorizontalGroup(
            registerDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(registryPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        registerDialogLayout.setVerticalGroup(
            registerDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(registryPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        registryPanel1.setBackground(new java.awt.Color(51, 153, 255));
        registryPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        registryPanel1.setForeground(new java.awt.Color(255, 255, 255));
        registryPanel1.setMaximumSize(new java.awt.Dimension(388, 359));
        registryPanel1.setMinimumSize(new java.awt.Dimension(388, 359));

        registryPanelTitle1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        registryPanelTitle1.setForeground(new java.awt.Color(255, 255, 255));
        registryPanelTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registryPanelTitle1.setText("Modificar Perfil");

        confirmPasswordRegistryLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        confirmPasswordRegistryLabel1.setForeground(new java.awt.Color(255, 255, 255));
        confirmPasswordRegistryLabel1.setText("Repetir contraseña:");

        passwordRegistryLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        passwordRegistryLabel1.setForeground(new java.awt.Color(255, 255, 255));
        passwordRegistryLabel1.setText("Contraseña: ");

        emailRegistryLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        emailRegistryLabel1.setForeground(new java.awt.Color(255, 255, 255));
        emailRegistryLabel1.setText("Correo electrónico:");

        userRegistryLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        userRegistryLabel1.setForeground(new java.awt.Color(255, 255, 255));
        userRegistryLabel1.setText("Nombre de Usuario:");

        destinarionComboBoxLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        destinarionComboBoxLabel1.setForeground(new java.awt.Color(255, 255, 255));
        destinarionComboBoxLabel1.setText("País");

        destinarionComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No lo se aún", "Polonia", "Rumanía", "Italia" }));
        destinarionComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destinarionComboBox1ActionPerformed(evt);
            }
        });

        goBackToLoginButton1.setText("Volver atrás");
        goBackToLoginButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBackToLoginButton1ActionPerformed(evt);
            }
        });

        registerBottonInRegister1.setText("Modificar");
        registerBottonInRegister1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBottonInRegister1ActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setOpaque(true);

        javax.swing.GroupLayout registryPanel1Layout = new javax.swing.GroupLayout(registryPanel1);
        registryPanel1.setLayout(registryPanel1Layout);
        registryPanel1Layout.setHorizontalGroup(
            registryPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registryPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(registryPanelTitle1)
                .addGap(114, 114, 114))
            .addGroup(registryPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(registryPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registryPanel1Layout.createSequentialGroup()
                        .addComponent(destinarionComboBoxLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registryPanel1Layout.createSequentialGroup()
                        .addGroup(registryPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(registryPanel1Layout.createSequentialGroup()
                                .addComponent(goBackToLoginButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(registerBottonInRegister1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(registryPanel1Layout.createSequentialGroup()
                                .addGroup(registryPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(passwordRegistryLabel1)
                                    .addComponent(confirmPasswordRegistryLabel1)
                                    .addComponent(emailRegistryLabel1)
                                    .addComponent(userRegistryLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(registryPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(destinarionComboBox1, javax.swing.GroupLayout.Alignment.TRAILING, 0, 220, Short.MAX_VALUE)
                                    .addComponent(confirmPasswordRegistryField1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(passwordRegistryField1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(emailRegistryField1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(28, 28, 28))))
        );
        registryPanel1Layout.setVerticalGroup(
            registryPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registryPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(registryPanelTitle1)
                .addGap(21, 21, 21)
                .addGroup(registryPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(userRegistryLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(registryPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailRegistryField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailRegistryLabel1))
                .addGap(18, 18, 18)
                .addGroup(registryPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordRegistryField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordRegistryLabel1))
                .addGap(18, 18, 18)
                .addGroup(registryPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmPasswordRegistryLabel1)
                    .addComponent(confirmPasswordRegistryField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(registryPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(destinarionComboBoxLabel1)
                    .addComponent(destinarionComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(registryPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(goBackToLoginButton1)
                    .addComponent(registerBottonInRegister1))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout modificarAlumnoDialogLayout = new javax.swing.GroupLayout(modificarAlumnoDialog.getContentPane());
        modificarAlumnoDialog.getContentPane().setLayout(modificarAlumnoDialogLayout);
        modificarAlumnoDialogLayout.setHorizontalGroup(
            modificarAlumnoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(registryPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        modificarAlumnoDialogLayout.setVerticalGroup(
            modificarAlumnoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(registryPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        registryPanel2.setBackground(new java.awt.Color(51, 153, 255));
        registryPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        registryPanel2.setForeground(new java.awt.Color(255, 255, 255));
        registryPanel2.setMaximumSize(new java.awt.Dimension(388, 359));
        registryPanel2.setMinimumSize(new java.awt.Dimension(388, 359));

        registryPanelTitle2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        registryPanelTitle2.setForeground(new java.awt.Color(255, 255, 255));
        registryPanelTitle2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registryPanelTitle2.setText("Modificar Perfil");

        confirmPasswordRegistryLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        confirmPasswordRegistryLabel2.setForeground(new java.awt.Color(255, 255, 255));
        confirmPasswordRegistryLabel2.setText("Repetir contraseña:");

        passwordRegistryLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        passwordRegistryLabel2.setForeground(new java.awt.Color(255, 255, 255));
        passwordRegistryLabel2.setText("Contraseña: ");

        emailRegistryLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        emailRegistryLabel2.setForeground(new java.awt.Color(255, 255, 255));
        emailRegistryLabel2.setText("Correo electrónico:");

        userRegistryLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        userRegistryLabel2.setForeground(new java.awt.Color(255, 255, 255));
        userRegistryLabel2.setText("Nombre de Usuario:");

        destinarionComboBoxLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        destinarionComboBoxLabel2.setForeground(new java.awt.Color(255, 255, 255));
        destinarionComboBoxLabel2.setText("País destino:");

        destinarionComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No lo se aún", "Polonia", "Rumanía", "Italia" }));
        destinarionComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destinarionComboBox2ActionPerformed(evt);
            }
        });

        goBackToLoginButton2.setText("Volver atrás");
        goBackToLoginButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBackToLoginButton2ActionPerformed(evt);
            }
        });

        registerBottonInRegister2.setText("Modificar");
        registerBottonInRegister2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBottonInRegister2ActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setOpaque(true);

        javax.swing.GroupLayout registryPanel2Layout = new javax.swing.GroupLayout(registryPanel2);
        registryPanel2.setLayout(registryPanel2Layout);
        registryPanel2Layout.setHorizontalGroup(
            registryPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registryPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(registryPanelTitle2)
                .addGap(114, 114, 114))
            .addGroup(registryPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(registryPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(registryPanel2Layout.createSequentialGroup()
                        .addComponent(goBackToLoginButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(registerBottonInRegister2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(registryPanel2Layout.createSequentialGroup()
                        .addGroup(registryPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passwordRegistryLabel2)
                            .addComponent(confirmPasswordRegistryLabel2)
                            .addComponent(emailRegistryLabel2)
                            .addComponent(userRegistryLabel2)
                            .addComponent(destinarionComboBoxLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(registryPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(destinarionComboBox2, javax.swing.GroupLayout.Alignment.TRAILING, 0, 220, Short.MAX_VALUE)
                            .addComponent(confirmPasswordRegistryField2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(passwordRegistryField2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(emailRegistryField2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(28, 28, 28))
        );
        registryPanel2Layout.setVerticalGroup(
            registryPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registryPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(registryPanelTitle2)
                .addGap(21, 21, 21)
                .addGroup(registryPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(userRegistryLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(registryPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailRegistryField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailRegistryLabel2))
                .addGap(18, 18, 18)
                .addGroup(registryPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordRegistryField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordRegistryLabel2))
                .addGap(18, 18, 18)
                .addGroup(registryPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmPasswordRegistryLabel2)
                    .addComponent(confirmPasswordRegistryField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(registryPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(destinarionComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(destinarionComboBoxLabel2))
                .addGap(25, 25, 25)
                .addGroup(registryPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(goBackToLoginButton2)
                    .addComponent(registerBottonInRegister2))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout modificarArrendadorDialogLayout = new javax.swing.GroupLayout(modificarArrendadorDialog.getContentPane());
        modificarArrendadorDialog.getContentPane().setLayout(modificarArrendadorDialogLayout);
        modificarArrendadorDialogLayout.setHorizontalGroup(
            modificarArrendadorDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(registryPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        modificarArrendadorDialogLayout.setVerticalGroup(
            modificarArrendadorDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(registryPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel1.setBackground(new java.awt.Color(46, 103, 212));

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.GridLayout(4, 2, 0, 10));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Fecha de Inicio (AAAA-MM-DD)");
        jPanel2.add(jLabel11);
        jPanel2.add(startDateField);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Fecha de Fin (AAAA-MM-DD)");
        jPanel2.add(jLabel12);
        jPanel2.add(endDateField);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Pasaporte");
        jPanel2.add(jLabel16);
        jPanel2.add(passportField);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Programa");
        jPanel2.add(jLabel13);

        mobilityCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ERASMUS", "MUNDUS", "SICUE" }));
        jPanel2.add(mobilityCombo);

        jPanel4.setOpaque(false);
        jPanel4.setLayout(new java.awt.GridLayout(1, 2, 30, 0));

        cancelStudentButton.setText("Cancelar");
        cancelStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelStudentButtonActionPerformed(evt);
            }
        });
        jPanel4.add(cancelStudentButton);

        acceptStudentButton.setText("Aceptar");
        acceptStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptStudentButtonActionPerformed(evt);
            }
        });
        jPanel4.add(acceptStudentButton);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Datos del Alumno");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout studentDataDialogLayout = new javax.swing.GroupLayout(studentDataDialog.getContentPane());
        studentDataDialog.getContentPane().setLayout(studentDataDialogLayout);
        studentDataDialogLayout.setHorizontalGroup(
            studentDataDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        studentDataDialogLayout.setVerticalGroup(
            studentDataDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(46, 103, 212));

        jPanel6.setOpaque(false);
        jPanel6.setLayout(new java.awt.GridLayout(2, 2, 30, 10));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Nº Fiscal");
        jPanel6.add(jLabel17);
        jPanel6.add(landlordNifField);

        cancelLanlordButton.setText("Cancelar");
        cancelLanlordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelLanlordButtonActionPerformed(evt);
            }
        });
        jPanel6.add(cancelLanlordButton);

        acceptLandlordButton.setText("Aceptar");
        acceptLandlordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptLandlordButtonActionPerformed(evt);
            }
        });
        jPanel6.add(acceptLandlordButton);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Datos del Arrendador");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout landlordDataDialogLayout = new javax.swing.GroupLayout(landlordDataDialog.getContentPane());
        landlordDataDialog.getContentPane().setLayout(landlordDataDialogLayout);
        landlordDataDialogLayout.setHorizontalGroup(
            landlordDataDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        landlordDataDialogLayout.setVerticalGroup(
            landlordDataDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel7.setBackground(new java.awt.Color(46, 103, 212));

        jPanel8.setOpaque(false);
        jPanel8.setLayout(new java.awt.GridLayout(3, 2, 30, 10));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Código Instiución");
        jPanel8.add(jLabel19);
        jPanel8.add(universityCodeField);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Institución Pública");
        jPanel8.add(jLabel21);

        universityPublicStatus.setForeground(new java.awt.Color(255, 255, 255));
        jPanel8.add(universityPublicStatus);

        cancelUniversityButton.setText("Cancelar");
        cancelUniversityButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelUniversityButtonActionPerformed(evt);
            }
        });
        jPanel8.add(cancelUniversityButton);

        acceptUniversityButton.setText("Aceptar");
        acceptUniversityButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptUniversityButtonActionPerformed(evt);
            }
        });
        jPanel8.add(acceptUniversityButton);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Datos de la Universidad");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout universityDataDialogLayout = new javax.swing.GroupLayout(universityDataDialog.getContentPane());
        universityDataDialog.getContentPane().setLayout(universityDataDialogLayout);
        universityDataDialogLayout.setHorizontalGroup(
            universityDataDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        universityDataDialogLayout.setVerticalGroup(
            universityDataDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        roomsLabel.setText("Rooms");

        avaliable_surfaceLabel.setText("Available Surface");

        durationLabel.setText("Duration");

        adv_idLabel.setText("adv_id");

        landlord_idLabel.setText("landlord_id");

        adv_idField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adv_idFieldActionPerformed(evt);
            }
        });

        jButton1.setText("Crear");

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialog2Layout.createSequentialGroup()
                        .addGroup(jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(avaliable_surfaceLabel)
                            .addGroup(jDialog2Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(roomsLabel)))
                        .addGap(101, 101, 101)
                        .addGroup(jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(avaliable_surfaceField, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                            .addComponent(roomsField)))
                    .addGroup(jDialog2Layout.createSequentialGroup()
                        .addGroup(jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(adv_idLabel)
                            .addComponent(durationLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(landlord_idLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(adv_idField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                            .addComponent(durationField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(landlord_idField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(85, 85, 85))
            .addGroup(jDialog2Layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roomsLabel)
                    .addComponent(roomsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(avaliable_surfaceLabel)
                    .addComponent(avaliable_surfaceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(durationLabel)
                    .addComponent(durationField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adv_idLabel)
                    .addComponent(adv_idField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(landlord_idLabel)
                    .addComponent(landlord_idField, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1024, 768));
        setResizable(false);

        profilePanel.setBackground(new java.awt.Color(46, 103, 212));

        logoPanel.setMaximumSize(new java.awt.Dimension(307, 70));
        logoPanel.setMinimumSize(new java.awt.Dimension(307, 70));
        logoPanel.setOpaque(false);
        logoPanel.setPreferredSize(new java.awt.Dimension(307, 70));

        logoPNG.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout logoPanelLayout = new javax.swing.GroupLayout(logoPanel);
        logoPanel.setLayout(logoPanelLayout);
        logoPanelLayout.setHorizontalGroup(
            logoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logoPNG, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        logoPanelLayout.setVerticalGroup(
            logoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logoPNG, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        UserPicturePanel.setOpaque(false);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout UserPicturePanelLayout = new javax.swing.GroupLayout(UserPicturePanel);
        UserPicturePanel.setLayout(UserPicturePanelLayout);
        UserPicturePanelLayout.setHorizontalGroup(
            UserPicturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserPicturePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        UserPicturePanelLayout.setVerticalGroup(
            UserPicturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        userDataPanel.setOpaque(false);
        userDataPanel.setLayout(new java.awt.GridLayout(5, 2));

        userTitleLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        userTitleLabel.setForeground(new java.awt.Color(255, 255, 255));
        userTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        userDataPanel.add(userTitleLabel);

        usernameLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(255, 255, 255));
        usernameLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        userDataPanel.add(usernameLabel);

        destinationTitleLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        destinationTitleLabel.setForeground(new java.awt.Color(255, 255, 255));
        destinationTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        userDataPanel.add(destinationTitleLabel);

        destinoLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        destinoLabel.setForeground(new java.awt.Color(255, 255, 255));
        destinoLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        userDataPanel.add(destinoLabel);

        usertypeTitleLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        usertypeTitleLabel.setForeground(new java.awt.Color(255, 255, 255));
        usertypeTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        userDataPanel.add(usertypeTitleLabel);

        userTypeLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        userTypeLabel.setForeground(new java.awt.Color(255, 255, 255));
        userTypeLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        userDataPanel.add(userTypeLabel);

        extraLabelTitle1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        extraLabelTitle1.setForeground(new java.awt.Color(255, 255, 255));
        extraLabelTitle1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        userDataPanel.add(extraLabelTitle1);

        extraLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        extraLabel1.setForeground(new java.awt.Color(255, 255, 255));
        extraLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        userDataPanel.add(extraLabel1);

        extraLabelTitle2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        extraLabelTitle2.setForeground(new java.awt.Color(255, 255, 255));
        extraLabelTitle2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        userDataPanel.add(extraLabelTitle2);

        extraLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        extraLabel2.setForeground(new java.awt.Color(255, 255, 255));
        extraLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        userDataPanel.add(extraLabel2);

        completeProfilePanel.setOpaque(false);

        completeProfileButton.setText("Completar mi Perfill");
        completeProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                completeProfileButtonActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Tu perfil no está completo");

        javax.swing.GroupLayout completeProfilePanelLayout = new javax.swing.GroupLayout(completeProfilePanel);
        completeProfilePanel.setLayout(completeProfilePanelLayout);
        completeProfilePanelLayout.setHorizontalGroup(
            completeProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, completeProfilePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(completeProfileButton)
                .addContainerGap())
        );
        completeProfilePanelLayout.setVerticalGroup(
            completeProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(completeProfilePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(completeProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(completeProfileButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout profilePanelLayout = new javax.swing.GroupLayout(profilePanel);
        profilePanel.setLayout(profilePanelLayout);
        profilePanelLayout.setHorizontalGroup(
            profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profilePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userDataPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(UserPicturePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
                    .addComponent(completeProfilePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        profilePanelLayout.setVerticalGroup(
            profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profilePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(UserPicturePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(userDataPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(completeProfilePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabbedPanel.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tabbedPanelStateChanged(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(profilePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabbedPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 612, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(profilePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tabbedPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        logoutMenu.setText("Usuario");
        logoutMenu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        closeSessionItem.setText("Cerrar Sesión");
        closeSessionItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeSessionItemActionPerformed(evt);
            }
        });
        logoutMenu.add(closeSessionItem);

        exitItem.setText("Salir");
        exitItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitItemActionPerformed(evt);
            }
        });
        logoutMenu.add(exitItem);

        menuBar.add(logoutMenu);

        editProfileMenu.setText("Editar Perfil");
        editProfileMenu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuBar.add(editProfileMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLoginActionPerformed
        String username = userTextField.getText();
        String password = passwordTextField.getText();
        if(loginSystem.login(username, password)){
            this.loginDialog.setVisible(false); //faltaba esta linea
            giveWelcome();
            updateUI();
        } else {
            JOptionPane.showMessageDialog(null, "Usuario o contraseña incorrecto", "Datos Erróneos", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bLoginActionPerformed

    private void giveWelcome() throws HeadlessException {
        String welcomeMessage = "¡Bienvendid@ de nuevo "+this.session.getUsername()+"!";
        JOptionPane.showMessageDialog(null, welcomeMessage, "Login Correcto", JOptionPane.INFORMATION_MESSAGE);
        if(this.session.getUserInstance() == null) {
            this.completeProfilePanel.setVisible(true);
        }
    }
    
    private Component[] getDataDialogs() {
        JDialog[] dataDialogs = new JDialog[4];
        dataDialogs[0] = this.studentDataDialog;
        dataDialogs[1] = this.landlordDataDialog;
        dataDialogs[2] = this.universityDataDialog;
        dataDialogs[3] = null;
        return dataDialogs;
    }
    
    private void updateUI() {
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/profile.png")));
        FXHelper.updateUserFields(this.session, this.userDataPanel.getComponents());
        FXHelper.updateTabbedPanel(this.session, this.tabbedPanel);
    }
    
    private void registerInLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerInLoginButtonActionPerformed
        this.loginDialog.setVisible(false);
        this.registerDialog.setVisible(true);
    }//GEN-LAST:event_registerInLoginButtonActionPerformed

    private void destinarionComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destinarionComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_destinarionComboBoxActionPerformed

    private void goBackToLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goBackToLoginButtonActionPerformed
        this.registerDialog.setVisible(false);
        this.loginDialog.setVisible(true);
    }//GEN-LAST:event_goBackToLoginButtonActionPerformed

    private void registerBottonInRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBottonInRegisterActionPerformed
        if(this.registrySystem.register(getRegitryData(), this.registerDialog)){
            JOptionPane.showMessageDialog(this.registerDialog, "Registro completado con éxito", "Registro correcto", JOptionPane.INFORMATION_MESSAGE);
            this.registerDialog.setVisible(false);
            this.loginDialog.setVisible(true);
        } 
    }//GEN-LAST:event_registerBottonInRegisterActionPerformed

    private void registerInLoginButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerInLoginButton1ActionPerformed
        this.closeApp();
    }//GEN-LAST:event_registerInLoginButton1ActionPerformed

    private void destinarionComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destinarionComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_destinarionComboBox1ActionPerformed

    private void goBackToLoginButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goBackToLoginButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_goBackToLoginButton1ActionPerformed

    private void registerBottonInRegister1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBottonInRegister1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerBottonInRegister1ActionPerformed

    private void destinarionComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destinarionComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_destinarionComboBox2ActionPerformed

    private void goBackToLoginButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goBackToLoginButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_goBackToLoginButton2ActionPerformed

    private void registerBottonInRegister2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBottonInRegister2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerBottonInRegister2ActionPerformed

    private void exitItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitItemActionPerformed
        this.closeApp();
    }//GEN-LAST:event_exitItemActionPerformed

    private void closeSessionItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeSessionItemActionPerformed
        this.closeSession();
    }//GEN-LAST:event_closeSessionItemActionPerformed

    private void completeProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_completeProfileButtonActionPerformed
        FXHelper.showCompleteDataDialog(this.session, this.getDataDialogs());
    }//GEN-LAST:event_completeProfileButtonActionPerformed

    private void acceptStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptStudentButtonActionPerformed
        String[] userData = {this.session.getCurrentUserData().getId(), 
                            this.startDateField.getText(),
                            this.endDateField.getText(),
                            this.passportField.getText(),
                            (String) this.mobilityCombo.getSelectedItem()};
        SQLHelper.addStudentData(userData);
        this.session.setUserInstance(this.session.getType(), this.session.getCurrentUserData());
        this.completeProfilePanel.setVisible(false);
        this.studentDataDialog.dispose();
        this.updateUI();
    }//GEN-LAST:event_acceptStudentButtonActionPerformed

    private void cancelStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelStudentButtonActionPerformed
        this.studentDataDialog.setVisible(false);
    }//GEN-LAST:event_cancelStudentButtonActionPerformed

    private void acceptLandlordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptLandlordButtonActionPerformed
        String[] userData = {this.session.getCurrentUserData().getId(), 
                            this.landlordNifField.getText()};
        SQLHelper.addLanlordData(userData);
        this.session.setUserInstance(this.session.getType(), this.session.getCurrentUserData());
        this.completeProfilePanel.setVisible(false);
        this.landlordDataDialog.dispose();
        this.updateUI();
    }//GEN-LAST:event_acceptLandlordButtonActionPerformed

    private void cancelLanlordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelLanlordButtonActionPerformed
        this.landlordDataDialog.setVisible(false);
    }//GEN-LAST:event_cancelLanlordButtonActionPerformed

    private void acceptUniversityButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptUniversityButtonActionPerformed
        String selectionStatus  = this.universityPublicStatus.isSelected() ?
                                    "1" : "0";
        String[] userData = {this.session.getCurrentUserData().getId(), 
                            this.universityCodeField.getText(),
                            selectionStatus};
        SQLHelper.addUniversityData(userData);
        this.session.setUserInstance(this.session.getType(), this.session.getCurrentUserData());
        this.completeProfilePanel.setVisible(false);
        this.universityDataDialog.dispose();
        this.updateUI();
    }//GEN-LAST:event_acceptUniversityButtonActionPerformed

    private void cancelUniversityButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelUniversityButtonActionPerformed
        this.universityDataDialog.setVisible(false);
    }//GEN-LAST:event_cancelUniversityButtonActionPerformed

    private void adv_idFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adv_idFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adv_idFieldActionPerformed

    private void tabbedPanelStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tabbedPanelStateChanged
        ((ExternalPanel) tabbedPanel.getSelectedComponent()).update();
    }//GEN-LAST:event_tabbedPanelStateChanged

    private RegisterData getRegitryData() {
        RegisterData registerData = new RegisterData();
        registerData.setUsername(this.userRegistryField.getText());
        registerData.setEmail(this.emailRegistryField.getText());
        registerData.setPassword(this.passwordRegistryField.getText());
        registerData.setConfirmPassword(this.confirmPasswordRegistryField.getText());
        registerData.setDestination(this.destinarionComboBox.getSelectedItem().toString());
        registerData.setType(getTypeFromCombobox());
        return registerData;
    }

    private String getTypeFromCombobox() {
        switch(this.userTypeComboBox.getSelectedItem().toString()){
            case "Estudiante":
                return "student";
            case "Arrendador":
                return "landlord";
            case "Universidad":
                return "uau";
        }
        return null;
    }
    
    private void closeApp(){
        try {
            SQLHelper.disconnect();
        } catch (SQLException ex) {
            Logger.getLogger(MyErasmus.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(this.registerDialog, "¡Hasta pronto!", "Cierre de Aplicación", JOptionPane.INFORMATION_MESSAGE);
        System.exit(0);
    }
    
    private void closeSession() {
        JOptionPane.showMessageDialog(this.registerDialog, "Sesión cerrada correctamente", "Cierre de Sesión", JOptionPane.INFORMATION_MESSAGE);
        this.loginSystem.logout();
        this.loginDialog.setVisible(true);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyErasmus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyErasmus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel UserPicturePanel;
    private javax.swing.JButton acceptLandlordButton;
    private javax.swing.JButton acceptStudentButton;
    private javax.swing.JButton acceptUniversityButton;
    private javax.swing.JTextField adv_idField;
    private javax.swing.JLabel adv_idLabel;
    private javax.swing.JTextField avaliable_surfaceField;
    private javax.swing.JLabel avaliable_surfaceLabel;
    private javax.swing.JButton bLogin;
    private javax.swing.JButton cancelLanlordButton;
    private javax.swing.JButton cancelStudentButton;
    private javax.swing.JButton cancelUniversityButton;
    private javax.swing.JMenuItem closeSessionItem;
    private javax.swing.JButton completeProfileButton;
    private javax.swing.JPanel completeProfilePanel;
    private javax.swing.JTextField confirmPasswordRegistryField;
    private javax.swing.JTextField confirmPasswordRegistryField1;
    private javax.swing.JTextField confirmPasswordRegistryField2;
    private javax.swing.JLabel confirmPasswordRegistryLabel;
    private javax.swing.JLabel confirmPasswordRegistryLabel1;
    private javax.swing.JLabel confirmPasswordRegistryLabel2;
    private javax.swing.JComboBox<String> destinarionComboBox;
    private javax.swing.JComboBox<String> destinarionComboBox1;
    private javax.swing.JComboBox<String> destinarionComboBox2;
    private javax.swing.JLabel destinarionComboBoxLabel;
    private javax.swing.JLabel destinarionComboBoxLabel1;
    private javax.swing.JLabel destinarionComboBoxLabel2;
    private javax.swing.JLabel destinationTitleLabel;
    private javax.swing.JLabel destinoLabel;
    private javax.swing.JTextField durationField;
    private javax.swing.JLabel durationLabel;
    private javax.swing.JMenu editProfileMenu;
    private javax.swing.JTextField emailRegistryField;
    private javax.swing.JTextField emailRegistryField1;
    private javax.swing.JTextField emailRegistryField2;
    private javax.swing.JLabel emailRegistryLabel;
    private javax.swing.JLabel emailRegistryLabel1;
    private javax.swing.JLabel emailRegistryLabel2;
    private javax.swing.JTextField endDateField;
    private javax.swing.JMenuItem exitItem;
    private javax.swing.JLabel extraLabel1;
    private javax.swing.JLabel extraLabel2;
    private javax.swing.JLabel extraLabelTitle1;
    private javax.swing.JLabel extraLabelTitle2;
    private javax.swing.JButton goBackToLoginButton;
    private javax.swing.JButton goBackToLoginButton1;
    private javax.swing.JButton goBackToLoginButton2;
    private javax.swing.JButton jButton1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JDialog landlordDataDialog;
    private javax.swing.JTextField landlordNifField;
    private javax.swing.JLabel landlord_idField;
    private javax.swing.JLabel landlord_idLabel;
    private javax.swing.JDialog loginDialog;
    private javax.swing.JLabel logoPNG;
    private javax.swing.JPanel logoPanel;
    private javax.swing.JMenu logoutMenu;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JComboBox<String> mobilityCombo;
    private javax.swing.JDialog modificarAlumnoDialog;
    private javax.swing.JDialog modificarArrendadorDialog;
    private javax.swing.JTextField passportField;
    private javax.swing.JTextField passwordRegistryField;
    private javax.swing.JTextField passwordRegistryField1;
    private javax.swing.JTextField passwordRegistryField2;
    private javax.swing.JLabel passwordRegistryLabel;
    private javax.swing.JLabel passwordRegistryLabel1;
    private javax.swing.JLabel passwordRegistryLabel2;
    private javax.swing.JTextField passwordTextField;
    private javax.swing.JPanel profilePanel;
    private javax.swing.JButton registerBottonInRegister;
    private javax.swing.JButton registerBottonInRegister1;
    private javax.swing.JButton registerBottonInRegister2;
    private javax.swing.JDialog registerDialog;
    private javax.swing.JButton registerInLoginButton;
    private javax.swing.JButton registerInLoginButton1;
    private javax.swing.JPanel registryPanel;
    private javax.swing.JPanel registryPanel1;
    private javax.swing.JPanel registryPanel2;
    private javax.swing.JLabel registryPanelTitle;
    private javax.swing.JLabel registryPanelTitle1;
    private javax.swing.JLabel registryPanelTitle2;
    private javax.swing.JTextField roomsField;
    private javax.swing.JLabel roomsLabel;
    private javax.swing.JTextField startDateField;
    private javax.swing.JDialog studentDataDialog;
    private javax.swing.JTabbedPane tabbedPanel;
    private javax.swing.JTextField universityCodeField;
    private javax.swing.JDialog universityDataDialog;
    private javax.swing.JCheckBox universityPublicStatus;
    private javax.swing.JPanel userDataPanel;
    private javax.swing.JTextField userRegistryField;
    private javax.swing.JLabel userRegistryLabel;
    private javax.swing.JLabel userRegistryLabel1;
    private javax.swing.JLabel userRegistryLabel2;
    private javax.swing.JTextField userTextField;
    private javax.swing.JLabel userTitleLabel;
    private javax.swing.JComboBox<String> userTypeComboBox;
    private javax.swing.JLabel userTypeComboBoxLabel;
    private javax.swing.JLabel userTypeLabel;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JLabel usertypeTitleLabel;
    // End of variables declaration//GEN-END:variables

}
