/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica2;

import java.awt.Color;
import java.awt.Font;
import java.math.RoundingMode;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import javax.swing.BorderFactory;
import javax.swing.JFormattedTextField;
import javax.swing.JFormattedTextField.AbstractFormatter;
import javax.swing.JFormattedTextField.AbstractFormatterFactory;
import javax.swing.text.InternationalFormatter;

/**
 *
 * @author santa
 */
public class Conversor extends javax.swing.JFrame {

    /**
     * Creates new form practica_2
     */
    public Conversor() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        upperPanel = new javax.swing.JPanel();
        ratioInputPanel = new javax.swing.JPanel();
        ratioInputField = new javax.swing.JFormattedTextField();
        convertButton = new javax.swing.JButton();
        convertButton2 = new javax.swing.JButton();
        lowerPanel = new javax.swing.JPanel();
        rightResultPanel = new javax.swing.JPanel();
        rightResultField = new javax.swing.JTextField();
        amountInputPanel = new javax.swing.JPanel();
        amountInputField = new javax.swing.JFormattedTextField();
        languageBar = new javax.swing.JMenuBar();
        esOpt = new javax.swing.JMenu();
        enOpt = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Conversor EUR(€) - USD($)");

        jPanel1.setName(""); // NOI18N

        upperPanel.setPreferredSize(new java.awt.Dimension(380, 100));

        ratioInputPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Tasa de Cambio (EUR -> USD)"));

        ratioInputField.setFormatterFactory(new AbstractFormatterFactory() {

            @Override
            public AbstractFormatter getFormatter(JFormattedTextField tf) {
                NumberFormat format = DecimalFormat.getInstance();
                format.setMinimumFractionDigits(2);
                format.setMaximumFractionDigits(2);
                format.setRoundingMode(RoundingMode.HALF_UP);
                InternationalFormatter formatter = new InternationalFormatter(format);
                formatter.setAllowsInvalid(false);
                formatter.setMinimum(0.0);
                formatter.setMaximum(10000.0);
                return formatter;
            }
        });
        ratioInputField.setText("0,00");

        javax.swing.GroupLayout ratioInputPanelLayout = new javax.swing.GroupLayout(ratioInputPanel);
        ratioInputPanel.setLayout(ratioInputPanelLayout);
        ratioInputPanelLayout.setHorizontalGroup(
            ratioInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ratioInputField, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
        );
        ratioInputPanelLayout.setVerticalGroup(
            ratioInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ratioInputField, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        convertButton.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        convertButton.setAlignmentX(0.5F);
        convertButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        convertButton.setDefaultCapable(false);
        convertButton.setLabel("€ >> $");
        convertButton.setMaximumSize(new java.awt.Dimension(58, 58));
        convertButton.setMinimumSize(new java.awt.Dimension(58, 58));
        convertButton.setPreferredSize(new java.awt.Dimension(60, 60));
        convertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertButtonActionPerformed(evt);
            }
        });

        convertButton2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        convertButton2.setAlignmentX(0.5F);
        convertButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        convertButton2.setDefaultCapable(false);
        convertButton2.setLabel("$ >> € ");
        convertButton2.setMaximumSize(new java.awt.Dimension(58, 58));
        convertButton2.setMinimumSize(new java.awt.Dimension(58, 58));
        convertButton2.setPreferredSize(new java.awt.Dimension(60, 60));
        convertButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout upperPanelLayout = new javax.swing.GroupLayout(upperPanel);
        upperPanel.setLayout(upperPanelLayout);
        upperPanelLayout.setHorizontalGroup(
            upperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(upperPanelLayout.createSequentialGroup()
                .addComponent(ratioInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(convertButton, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(convertButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        upperPanelLayout.setVerticalGroup(
            upperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(upperPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(upperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(convertButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(convertButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, upperPanelLayout.createSequentialGroup()
                        .addGap(0, 2, Short.MAX_VALUE)
                        .addComponent(ratioInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        rightResultPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultado"));
        rightResultPanel.setPreferredSize(new java.awt.Dimension(320, 64));

        rightResultField.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        rightResultField.setBorder(null);
        rightResultField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        rightResultField.setEnabled(false);
        rightResultField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rightResultFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout rightResultPanelLayout = new javax.swing.GroupLayout(rightResultPanel);
        rightResultPanel.setLayout(rightResultPanelLayout);
        rightResultPanelLayout.setHorizontalGroup(
            rightResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rightResultField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
        );
        rightResultPanelLayout.setVerticalGroup(
            rightResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rightResultField, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
        );

        amountInputPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Cantidad\n"));
        amountInputPanel.setPreferredSize(new java.awt.Dimension(350, 64));

        amountInputField.setFormatterFactory(new AbstractFormatterFactory() {

            @Override
            public AbstractFormatter getFormatter(JFormattedTextField tf) {
                NumberFormat format = DecimalFormat.getInstance();
                format.setMinimumFractionDigits(2);
                format.setMaximumFractionDigits(2);
                format.setRoundingMode(RoundingMode.HALF_UP);
                InternationalFormatter formatter = new InternationalFormatter(format);
                formatter.setAllowsInvalid(false);
                formatter.setMinimum(0.0);
                formatter.setMaximum(10000.0);
                return formatter;
            }
        });
        amountInputField.setText("0,00");

        javax.swing.GroupLayout amountInputPanelLayout = new javax.swing.GroupLayout(amountInputPanel);
        amountInputPanel.setLayout(amountInputPanelLayout);
        amountInputPanelLayout.setHorizontalGroup(
            amountInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(amountInputField, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
        );
        amountInputPanelLayout.setVerticalGroup(
            amountInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(amountInputField)
        );

        javax.swing.GroupLayout lowerPanelLayout = new javax.swing.GroupLayout(lowerPanel);
        lowerPanel.setLayout(lowerPanelLayout);
        lowerPanelLayout.setHorizontalGroup(
            lowerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lowerPanelLayout.createSequentialGroup()
                .addComponent(amountInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rightResultPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        lowerPanelLayout.setVerticalGroup(
            lowerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lowerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lowerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(amountInputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                    .addComponent(rightResultPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lowerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(upperPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 782, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(upperPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lowerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        languageBar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        esOpt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        esOpt.setLabel("ES");
        esOpt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                esOptMouseClicked(evt);
            }
        });
        languageBar.add(esOpt);

        enOpt.setBorderPainted(true);
        enOpt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        enOpt.setLabel("EN");
        enOpt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enOptMouseClicked(evt);
            }
        });
        languageBar.add(enOpt);

        setJMenuBar(languageBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 802, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 208, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void convertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertButtonActionPerformed
        eurosToDollars();
    }//GEN-LAST:event_convertButtonActionPerformed

    private void convertButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertButton2ActionPerformed
        dollarsToEuros();
    }//GEN-LAST:event_convertButton2ActionPerformed

    
    /**
     * Language functions
     */
    
    private void enOptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enOptMouseClicked
        this.amountInputPanel.setBorder(BorderFactory.createTitledBorder("Amount"));
        this.ratioInputPanel.setBorder(BorderFactory.createTitledBorder("Change Ratio (EUR -> USD)"));
        this.rightResultPanel.setBorder(BorderFactory.createTitledBorder("Result"));
        this.esOpt.setFont(new Font("Segoe UI", Font.PLAIN, 18));
        this.enOpt.setFont(new Font("Segoe UI", Font.BOLD, 18));
    }//GEN-LAST:event_enOptMouseClicked

    private void esOptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_esOptMouseClicked
        this.amountInputPanel.setBorder(BorderFactory.createTitledBorder("Cantidad"));
        this.ratioInputPanel.setBorder(BorderFactory.createTitledBorder("Tasa de cambio (EUR -> USD)"));
        this.rightResultPanel.setBorder(BorderFactory.createTitledBorder("Resultado"));
        this.esOpt.setFont(new Font("Segoe UI", Font.BOLD, 18));
        this.enOpt.setFont(new Font("Segoe UI", Font.PLAIN, 18));
    }//GEN-LAST:event_esOptMouseClicked

    private void rightResultFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rightResultFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rightResultFieldActionPerformed

    
    

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Conversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Conversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Conversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Conversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Conversor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField amountInputField;
    private javax.swing.JPanel amountInputPanel;
    private javax.swing.JButton convertButton;
    private javax.swing.JButton convertButton2;
    private javax.swing.JMenu enOpt;
    private javax.swing.JMenu esOpt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuBar languageBar;
    private javax.swing.JPanel lowerPanel;
    private javax.swing.JFormattedTextField ratioInputField;
    private javax.swing.JPanel ratioInputPanel;
    private javax.swing.JTextField rightResultField;
    private javax.swing.JPanel rightResultPanel;
    private javax.swing.JPanel upperPanel;
    // End of variables declaration//GEN-END:variables

    //Logic functions
    private void dollarsToEuros() {
        //dummy
        this.rightResultField.setText(String.format("%,.2f", this.convertUsdToEur())+ " EUR (€)");
        this.amountInputField.setText(getAmountFieldToText());
        updateFxRL();
    }

    private void eurosToDollars() {
        this.rightResultField.setText(String.format("%,.2f", this.convertEurToUsd()) + " USD ($)");
        this.amountInputField.setText(getAmountFieldToText());
        updateFxLR();
    }
    

    //Conversion functions
    private double convertUsdToEur() {
        String strAmount = this.formatToDouble(this.amountInputField.getText());
        String strRatio = this.formatToDouble(this.ratioInputField.getText());
        double amount = (strAmount.equals("")) ? 0.00 : Double.parseDouble(strAmount);
        double ratio = (strRatio.equals("")) ? 0.00 : Double.parseDouble(strRatio);
        return (ratio == 0.00) ? 0.00 : amount*(1/ratio);
    }

    private double convertEurToUsd() {
        String strAmount = this.formatToDouble(this.amountInputField.getText());
        String strRatio = this.formatToDouble(this.ratioInputField.getText());
        double amount = (strAmount.equals("")) ? 0.00 : Double.parseDouble(strAmount);
        double ratio = (strRatio.equals("")) ? 0.00 : Double.parseDouble(strRatio);
        return amount*ratio;
    }    
    
    private String formatToDouble(String number){
        String res = number.replace(".", ":");
        res = res.replace(",", ".");
        res = res.replace(":", "");
        return res;
    }

    //Graphic functions
    private void updateFxLR() {
        this.convertButton.setBackground(Color.black);
        this.convertButton.setForeground(Color.white);
        this.convertButton2.setBackground(new Color(240,240,240));
        this.convertButton2.setForeground(Color.black);
    }

    private void updateFxRL() {
        this.convertButton2.setBackground(Color.black);
        this.convertButton2.setForeground(Color.white);
        this.convertButton.setBackground(new Color(240,240,240));
        this.convertButton.setForeground(Color.black);
    }

    private String getAmountFieldToText() {
        return (this.amountInputField.getText().equals("")) ? "0.00" : this.amountInputField.getText();
    }
}
